-- CreateTable
CREATE TABLE "Material" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "subcategory" TEXT NOT NULL,
    "symbol" TEXT,
    "density" DOUBLE PRECISION NOT NULL,
    "youngsModulus" DOUBLE PRECISION NOT NULL,
    "yieldStrength" DOUBLE PRECISION NOT NULL,
    "ultimateStrength" DOUBLE PRECISION NOT NULL,
    "thermalConductivity" DOUBLE PRECISION NOT NULL,
    "electricalConductivity" DOUBLE PRECISION NOT NULL,
    "thermalExpansion" DOUBLE PRECISION NOT NULL,
    "specificHeat" DOUBLE PRECISION NOT NULL,
    "meltingPoint" DOUBLE PRECISION NOT NULL,
    "maxOperatingTemp" DOUBLE PRECISION NOT NULL,
    "resistivity" DOUBLE PRECISION NOT NULL,
    "dielectricStrength" DOUBLE PRECISION,
    "hardness" DOUBLE PRECISION,
    "color" TEXT NOT NULL,
    "isStretchable" BOOLEAN NOT NULL DEFAULT false,
    "isConductive" BOOLEAN NOT NULL DEFAULT false,
    "isInsulating" BOOLEAN NOT NULL DEFAULT false,
    "isMagnetic" BOOLEAN NOT NULL DEFAULT false,
    "isTransparent" BOOLEAN NOT NULL DEFAULT false,
    "isBiodegradable" BOOLEAN NOT NULL DEFAULT false,
    "imageUrl" TEXT,
    "description" TEXT NOT NULL,
    "applications" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Material_pkey" PRIMARY KEY ("id")
);
