// observability/logging/constants/logging-events.ts
export enum LogEvents {
  // --- Database & Prisma (Handled by Filter & Service) ---
  DATABASE_ERROR = 'DATABASE_ERROR',
  DATABASE_UNAVAILABLE = 'DATABASE_UNAVAILABLE',
  DATABASE_QUERY_FAILED = 'DATABASE_QUERY_FAILED',
  DATABASE_UNKNOWN_ERROR = 'DATABASE_UNKNOWN_ERROR',
  DATABASE_VALIDATION_ERROR = 'DATABASE_VALIDATION_ERROR',

  PRISMA_QUERY = 'PRISMA_QUERY',
  PRISMA_INFO = 'PRISMA_INFO',
  PRISMA_WARN = 'PRISMA_WARN',
  PRISMA_ERROR = 'PRISMA_ERROR',
  DATABASE_CONNECTING = 'DATABASE_CONNECTING',
  DATABASE_CONNECTED = 'DATABASE_CONNECTED',
  DATABASE_CONNECTION_FAILED = 'DATABASE_CONNECTION_FAILED',
  DATABASE_DISCONNECTED = 'DATABASE_DISCONNECTED',

  // Users
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_PASSWORD_UPDATED = 'USER_PASSWORD_UPDATED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_DELETED = 'USER_DELETED',

  //Auth
  AUTH_REGISTER = 'AUTH_REGISTER',
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_REFRESH = 'AUTH.REFRESH',
  AUTH_PASSWORD_RESET_REQUEST = 'AUTH.PASSWORD.RESET.REQUEST',
  AUTH_PASSWORD_RESET_SUCCESS = 'AUTH.PASSWORD.RESET.SUCCESS',
  AUTH_PASSWORD_CHANGE = 'AUTH.PASSWORD.CHANGE',
  AUTH_EMAIL_VERIFICATION_REQUEST = 'AUTH.EMAIL.VERIFICATION.REQUEST',
  AUTH_EMAIL_VERIFICATION_SUCCESS = 'AUTH.EMAIL.VERIFICATION.SUCCESS',

  // Organizations
  ORGANIZATION_CREATED = 'ORGANIZATION_CREATED',
  ORGANIZATION_UPDATED = 'ORGANIZATION_UPDATED',
  ORGANIZATION_DELETED = 'ORGANIZATION_DELETED',
  MEMBERSHIP_ROLE_UPDATED = 'MEMBERSHIP_ROLE_UPDATED',
  MEMBERSHIP_REMOVED = 'MEMBERSHIP_REMOVED',

  //Invitations
  INVITATION_SENT = 'INVITATION_SENT',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
  INVITATION_DECLINED = 'INVITATION_DECLINED',

  // Email
  EMAIL_VERIFICATION_SENT = 'EMAIL.VERIFICATION.SENT',
  EMAIL_VERIFICATION_FAILED = 'EMAIL.VERIFICATION.FAILED',
  EMAIL_VERIFICATION_RESENT = 'EMAIL.VERIFICATION.RESENT',
  EMAIL_PASSWORD_RESET_SENT = 'EMAIL.PASSWORD.RESET.SENT',
  EMAIL_PASSWORD_RESET_FAILED = 'EMAIL.PASSWORD.RESET.FAILED',
  EMAIL_SENT = 'EMAIL.SENT',

  // Sessions
  SESSION_CREATED = 'SESSION.CREATED',
  SESSION_REVOKED = 'SESSION.REVOKED',
  SESSION_REVOKED_ALL = 'SESSION.REVOKED.ALL',
  SESSION_CLEANUP = 'SESSION.CLEANUP',

  // Password Reset
  PASSWORD_RESET_REQUESTED = 'PASSWORD.RESET.REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD.RESET.COMPLETED',
  PASSWORD_RESET_FAILED = 'PASSWORD.RESET.FAILED',
}
/**
export const LogEvents = {
  // --- PrismaService Lifecycle & Event Tracking ---
  PRISMA_QUERY = 'PRISMA_QUERY',
  PRISMA_INFO = 'PRISMA_INFO',
  PRISMA_WARN = 'PRISMA_WARN',
  PRISMA_ERROR = 'PRISMA_ERROR',
  
  DATABASE_CONNECTING = 'DATABASE_CONNECTING',
  DATABASE_CONNECTED = 'DATABASE_CONNECTED',
  DATABASE_CONNECTION_FAILED = 'DATABASE_CONNECTION_FAILED',
  DATABASE_DISCONNECTED = 'DATABASE_DISCONNECTED',

  // --- LoggingExceptionFilter Classifications (New) ---
  DATABASE_ERROR = 'DATABASE_ERROR',
  DATABASE_UNAVAILABLE = 'DATABASE_UNAVAILABLE',
  DATABASE_QUERY_FAILED = 'DATABASE_QUERY_FAILED',
  DATABASE_UNKNOWN_ERROR = 'DATABASE_UNKNOWN_ERROR',
  DATABASE_VALIDATION_ERROR = 'DATABASE_VALIDATION_ERROR',

  // Authentication
  AUTH_REGISTER: 'auth.register',
  AUTH_LOGIN: 'auth.login',
  AUTH_LOGOUT: 'auth.logout',
  AUTH_REFRESH: 'auth.refresh',
  AUTH_PASSWORD_RESET_REQUEST: 'auth.password.reset.request',
  AUTH_PASSWORD_RESET_SUCCESS: 'auth.password.reset.success',
  AUTH_PASSWORD_CHANGE: 'auth.password.change',
  AUTH_EMAIL_VERIFICATION_REQUEST: 'auth.email.verification.request',
  AUTH_EMAIL_VERIFICATION_SUCCESS: 'auth.email.verification.success',

  // Users
  USER_CREATED: 'user.created',
  USER_UPDATED: 'user.updated',
  USER_ACTIVATED: 'user.activated',
  USER_DEACTIVATED: 'user.deactivated',
  USER_DELETED: 'user.deleted',
  USER_PASSWORD_UPDATED: 'user.password.updated',

  // Organizations
  ORGANIZATION_CREATED: 'organization.created',
  ORGANIZATION_UPDATED: 'organization.updated',
  ORGANIZATION_DELETED: 'organization.deleted',
  ORGANIZATION_VIEWED: 'organization.viewed',
  ORGANIZATION_MEMBER_ADDED: 'organization.member.added',
  ORGANIZATION_MEMBER_REMOVED: 'organization.member.removed',

  // Memberships
  MEMBERSHIP_CREATED: 'membership.created',
  MEMBERSHIP_UPDATED: 'membership.updated',
  MEMBERSHIP_REMOVED: 'membership.removed',
  MEMBERSHIP_ROLE_UPDATED: 'membership.role.updated',

  // Invitations
  INVITATION_SENT: 'invitation.sent',
  INVITATION_ACCEPTED: 'invitation.accepted',
  INVITATION_DECLINED: 'invitation.declined',

  

  // Tasks / Projects
  TASK_CREATED: 'task.created',
  TASK_UPDATED: 'task.updated',
  TASK_COMPLETED: 'task.completed',

  // Notifications & Emails
  NOTIFICATION_SENT: 'notification.sent',
  EMAIL_SENT: 'email.sent',
  EMAIL_FAILED: 'email.failed',

  // Background Jobs
  BACKGROUND_JOB_STARTED: 'background-job.started',
  BACKGROUND_JOB_COMPLETED: 'background-job.completed',
  BACKGROUND_JOB_FAILED: 'background-job.failed',

  // External APIs
  EXTERNAL_API_CALL: 'external-api.called',
  EXTERNAL_API_FAILED: 'external-api.failed',

  // Process
  PROCESS_UNCAUGHT_EXCEPTION: 'process.uncaughtException',
  PROCESS_UNHANDLED_REJECTION: 'process.unhandledRejection',

} as const;

export type LogEvent = (typeof LogEvents)[keyof typeof LogEvents];
**/
